version: '2'

services:
  ownphotos:
    image: ownphotos
    build: .

    ports:
      - 8000:80
      - 8001:5000

    volumes:
      - $HOME/Pictures/:/data

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: database
      DB_BACKEND: postgresql
      DB_NAME: ownphotos
      DB_USER: ownphotos
      DB_PASS: ownphotos
      DB_PORT: 5432

      SECRET_KEY: CHANGE_ME
      ADMIN_EMAIL: CHANGE_ME
      ADMIN_USERNAME: CHANGE_ME
      ADMIN_PASSWORD: CHANGE_ME
      DEBUG: "false"
      MAPBOX_API_KEY: CHANGE_ME
      BACKEND_HOST: CHANGE_ME

    depends_on:
      - database
      - redis

  redis:
    image: redis
    restart: always
    volumes:
      - /data

  database:
    image: postgres
    environment:
      POSTGRES_DB: ownphotos
      POSTGRES_USER: ownphotos
      POSTGRES_PASSWORD: ownphotos
    volumes:
      - /var/lib/postgresql/data

